// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use gio;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::GString;
use glib_sys;
use gobject;
use ibus_sys;
use libc;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use ExtensionEvent;
use LookupTable;
use Object;
use PropList;
use Property;
use Service;
use Text;

glib_wrapper! {
    pub struct PanelService(Object<ibus_sys::IBusPanelService, ibus_sys::IBusPanelServiceClass, PanelServiceClass>) @extends Service, Object, gobject::InitiallyUnowned;

    match fn {
        get_type => || ibus_sys::ibus_panel_service_get_type(),
    }
}

impl PanelService {
    pub fn new(connection: &gio::DBusConnection) -> PanelService {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ibus_sys::ibus_panel_service_new(connection.to_glib_none().0))
        }
    }
}

pub const NONE_PANEL_SERVICE: Option<&PanelService> = None;

pub trait PanelServiceExt: 'static {
    fn candidate_clicked(&self, index: u32, button: u32, state: u32);

    fn commit_text<P: IsA<Text>>(&self, text: &P);

    fn cursor_down(&self);

    fn cursor_up(&self);

    fn hide_preedit_text_received(&self);

    fn page_down(&self);

    fn page_up(&self);

    fn panel_extension<P: IsA<ExtensionEvent>>(&self, event: &P);

    //fn panel_extension_register_keys(&self, first_property_name: &str, : /*Unknown conversion*//*Unimplemented*/Fundamental: VarArgs);

    fn property_activate(&self, prop_name: &str, prop_state: u32);

    fn property_hide(&self, prop_name: &str);

    fn property_show(&self, prop_name: &str);

    fn show_preedit_text_received(&self);

    fn update_auxiliary_text_received<P: IsA<Text>>(&self, text: &P, visible: bool);

    fn update_lookup_table_received<P: IsA<LookupTable>>(&self, table: &P, visible: bool);

    fn update_preedit_text_received<P: IsA<Text>>(&self, text: &P, cursor_pos: u32, visible: bool);

    fn connect_candidate_clicked_lookup_table<F: Fn(&Self, u32, u32, u32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_commit_text_received<F: Fn(&Self, &Text) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_cursor_down_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_cursor_up_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_destroy_context<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_focus_in<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_focus_out<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_hide_auxiliary_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_hide_language_bar<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_hide_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_hide_preedit_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_page_down_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_page_up_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_panel_extension_received<F: Fn(&Self, &ExtensionEvent) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_process_key_event<F: Fn(&Self, u32, u32, u32) -> bool + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_register_properties<F: Fn(&Self, &PropList) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_reset<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_set_content_type<F: Fn(&Self, u32, u32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_set_cursor_location<F: Fn(&Self, i32, i32, i32, i32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_set_cursor_location_relative<F: Fn(&Self, i32, i32, i32, i32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_show_auxiliary_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_show_language_bar<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_show_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_show_preedit_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_start_setup<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_state_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_update_auxiliary_text<F: Fn(&Self, &Text, bool) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_update_lookup_table<F: Fn(&Self, &LookupTable, bool) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_update_preedit_text<F: Fn(&Self, &Text, u32, bool) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_update_property<F: Fn(&Self, &Property) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<PanelService>> PanelServiceExt for O {
    fn candidate_clicked(&self, index: u32, button: u32, state: u32) {
        unsafe {
            ibus_sys::ibus_panel_service_candidate_clicked(self.as_ref().to_glib_none().0, index, button, state);
        }
    }

    fn commit_text<P: IsA<Text>>(&self, text: &P) {
        unsafe {
            ibus_sys::ibus_panel_service_commit_text(self.as_ref().to_glib_none().0, text.as_ref().to_glib_none().0);
        }
    }

    fn cursor_down(&self) {
        unsafe {
            ibus_sys::ibus_panel_service_cursor_down(self.as_ref().to_glib_none().0);
        }
    }

    fn cursor_up(&self) {
        unsafe {
            ibus_sys::ibus_panel_service_cursor_up(self.as_ref().to_glib_none().0);
        }
    }

    fn hide_preedit_text_received(&self) {
        unsafe {
            ibus_sys::ibus_panel_service_hide_preedit_text_received(self.as_ref().to_glib_none().0);
        }
    }

    fn page_down(&self) {
        unsafe {
            ibus_sys::ibus_panel_service_page_down(self.as_ref().to_glib_none().0);
        }
    }

    fn page_up(&self) {
        unsafe {
            ibus_sys::ibus_panel_service_page_up(self.as_ref().to_glib_none().0);
        }
    }

    fn panel_extension<P: IsA<ExtensionEvent>>(&self, event: &P) {
        unsafe {
            ibus_sys::ibus_panel_service_panel_extension(self.as_ref().to_glib_none().0, event.as_ref().to_glib_full());
        }
    }

    //fn panel_extension_register_keys(&self, first_property_name: &str, : /*Unknown conversion*//*Unimplemented*/Fundamental: VarArgs) {
    //    unsafe { TODO: call ibus_sys:ibus_panel_service_panel_extension_register_keys() }
    //}

    fn property_activate(&self, prop_name: &str, prop_state: u32) {
        unsafe {
            ibus_sys::ibus_panel_service_property_activate(self.as_ref().to_glib_none().0, prop_name.to_glib_none().0, prop_state);
        }
    }

    fn property_hide(&self, prop_name: &str) {
        unsafe {
            ibus_sys::ibus_panel_service_property_hide(self.as_ref().to_glib_none().0, prop_name.to_glib_none().0);
        }
    }

    fn property_show(&self, prop_name: &str) {
        unsafe {
            ibus_sys::ibus_panel_service_property_show(self.as_ref().to_glib_none().0, prop_name.to_glib_none().0);
        }
    }

    fn show_preedit_text_received(&self) {
        unsafe {
            ibus_sys::ibus_panel_service_show_preedit_text_received(self.as_ref().to_glib_none().0);
        }
    }

    fn update_auxiliary_text_received<P: IsA<Text>>(&self, text: &P, visible: bool) {
        unsafe {
            ibus_sys::ibus_panel_service_update_auxiliary_text_received(self.as_ref().to_glib_none().0, text.as_ref().to_glib_none().0, visible.to_glib());
        }
    }

    fn update_lookup_table_received<P: IsA<LookupTable>>(&self, table: &P, visible: bool) {
        unsafe {
            ibus_sys::ibus_panel_service_update_lookup_table_received(self.as_ref().to_glib_none().0, table.as_ref().to_glib_none().0, visible.to_glib());
        }
    }

    fn update_preedit_text_received<P: IsA<Text>>(&self, text: &P, cursor_pos: u32, visible: bool) {
        unsafe {
            ibus_sys::ibus_panel_service_update_preedit_text_received(self.as_ref().to_glib_none().0, text.as_ref().to_glib_none().0, cursor_pos, visible.to_glib());
        }
    }

    fn connect_candidate_clicked_lookup_table<F: Fn(&Self, u32, u32, u32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn candidate_clicked_lookup_table_trampoline<P, F: Fn(&P, u32, u32, u32) + 'static>(this: *mut ibus_sys::IBusPanelService, object: libc::c_uint, p0: libc::c_uint, p1: libc::c_uint, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), object, p0, p1)
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"candidate-clicked-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(candidate_clicked_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_commit_text_received<F: Fn(&Self, &Text) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn commit_text_received_trampoline<P, F: Fn(&P, &Text) + 'static>(this: *mut ibus_sys::IBusPanelService, text: *mut ibus_sys::IBusText, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(text))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"commit-text-received\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(commit_text_received_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_cursor_down_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn cursor_down_lookup_table_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"cursor-down-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(cursor_down_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_cursor_up_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn cursor_up_lookup_table_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"cursor-up-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(cursor_up_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_destroy_context<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn destroy_context_trampoline<P, F: Fn(&P, &str) + 'static>(this: *mut ibus_sys::IBusPanelService, input_context_path: *mut libc::c_char, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &GString::from_glib_borrow(input_context_path))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"destroy-context\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(destroy_context_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_focus_in<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn focus_in_trampoline<P, F: Fn(&P, &str) + 'static>(this: *mut ibus_sys::IBusPanelService, input_context_path: *mut libc::c_char, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &GString::from_glib_borrow(input_context_path))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"focus-in\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(focus_in_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_focus_out<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn focus_out_trampoline<P, F: Fn(&P, &str) + 'static>(this: *mut ibus_sys::IBusPanelService, input_context_path: *mut libc::c_char, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &GString::from_glib_borrow(input_context_path))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"focus-out\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(focus_out_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_hide_auxiliary_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn hide_auxiliary_text_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"hide-auxiliary-text\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(hide_auxiliary_text_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_hide_language_bar<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn hide_language_bar_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"hide-language-bar\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(hide_language_bar_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_hide_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn hide_lookup_table_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"hide-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(hide_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_hide_preedit_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn hide_preedit_text_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"hide-preedit-text\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(hide_preedit_text_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_page_down_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn page_down_lookup_table_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"page-down-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(page_down_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_page_up_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn page_up_lookup_table_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"page-up-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(page_up_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_panel_extension_received<F: Fn(&Self, &ExtensionEvent) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn panel_extension_received_trampoline<P, F: Fn(&P, &ExtensionEvent) + 'static>(this: *mut ibus_sys::IBusPanelService, data: *mut ibus_sys::IBusExtensionEvent, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(data))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"panel-extension-received\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(panel_extension_received_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_process_key_event<F: Fn(&Self, u32, u32, u32) -> bool + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn process_key_event_trampoline<P, F: Fn(&P, u32, u32, u32) -> bool + 'static>(this: *mut ibus_sys::IBusPanelService, keyval: libc::c_uint, keycode: libc::c_uint, state: libc::c_uint, f: glib_sys::gpointer) -> glib_sys::gboolean
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), keyval, keycode, state).to_glib()
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"process-key-event\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(process_key_event_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_register_properties<F: Fn(&Self, &PropList) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn register_properties_trampoline<P, F: Fn(&P, &PropList) + 'static>(this: *mut ibus_sys::IBusPanelService, prop_list: *mut ibus_sys::IBusPropList, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(prop_list))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"register-properties\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(register_properties_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_reset<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn reset_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"reset\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(reset_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_set_content_type<F: Fn(&Self, u32, u32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn set_content_type_trampoline<P, F: Fn(&P, u32, u32) + 'static>(this: *mut ibus_sys::IBusPanelService, purpose: libc::c_uint, hints: libc::c_uint, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), purpose, hints)
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"set-content-type\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(set_content_type_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_set_cursor_location<F: Fn(&Self, i32, i32, i32, i32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn set_cursor_location_trampoline<P, F: Fn(&P, i32, i32, i32, i32) + 'static>(this: *mut ibus_sys::IBusPanelService, x: libc::c_int, y: libc::c_int, w: libc::c_int, h: libc::c_int, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), x, y, w, h)
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"set-cursor-location\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(set_cursor_location_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_set_cursor_location_relative<F: Fn(&Self, i32, i32, i32, i32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn set_cursor_location_relative_trampoline<P, F: Fn(&P, i32, i32, i32, i32) + 'static>(this: *mut ibus_sys::IBusPanelService, x: libc::c_int, y: libc::c_int, w: libc::c_int, h: libc::c_int, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), x, y, w, h)
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"set-cursor-location-relative\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(set_cursor_location_relative_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_show_auxiliary_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn show_auxiliary_text_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"show-auxiliary-text\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(show_auxiliary_text_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_show_language_bar<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn show_language_bar_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"show-language-bar\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(show_language_bar_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_show_lookup_table<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn show_lookup_table_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"show-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(show_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_show_preedit_text<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn show_preedit_text_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"show-preedit-text\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(show_preedit_text_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_start_setup<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn start_setup_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"start-setup\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(start_setup_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_state_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn state_changed_trampoline<P, F: Fn(&P) + 'static>(this: *mut ibus_sys::IBusPanelService, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"state-changed\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(state_changed_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_update_auxiliary_text<F: Fn(&Self, &Text, bool) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn update_auxiliary_text_trampoline<P, F: Fn(&P, &Text, bool) + 'static>(this: *mut ibus_sys::IBusPanelService, text: *mut ibus_sys::IBusText, visible: glib_sys::gboolean, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(text), from_glib(visible))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"update-auxiliary-text\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(update_auxiliary_text_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_update_lookup_table<F: Fn(&Self, &LookupTable, bool) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn update_lookup_table_trampoline<P, F: Fn(&P, &LookupTable, bool) + 'static>(this: *mut ibus_sys::IBusPanelService, lookup_table: *mut ibus_sys::IBusLookupTable, visible: glib_sys::gboolean, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(lookup_table), from_glib(visible))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"update-lookup-table\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(update_lookup_table_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_update_preedit_text<F: Fn(&Self, &Text, u32, bool) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn update_preedit_text_trampoline<P, F: Fn(&P, &Text, u32, bool) + 'static>(this: *mut ibus_sys::IBusPanelService, text: *mut ibus_sys::IBusText, cursor_pos: libc::c_uint, visible: glib_sys::gboolean, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(text), cursor_pos, from_glib(visible))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"update-preedit-text\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(update_preedit_text_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_update_property<F: Fn(&Self, &Property) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn update_property_trampoline<P, F: Fn(&P, &Property) + 'static>(this: *mut ibus_sys::IBusPanelService, prop: *mut ibus_sys::IBusProperty, f: glib_sys::gpointer)
            where P: IsA<PanelService>
        {
            let f: &F = &*(f as *const F);
            f(&PanelService::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(prop))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"update-property\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(update_property_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for PanelService {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "PanelService")
    }
}
