// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use ibus_sys;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct XML(Boxed<ibus_sys::IBusXML>);

    match fn {
        copy => |ptr| ibus_sys::ibus_xml_copy(mut_override(ptr)),
        free => |ptr| ibus_sys::ibus_xml_free(ptr),
        get_type => || ibus_sys::ibus_xml_get_type(),
    }
}

impl XML {
    //pub fn output(&self, output: /*Ignored*/&mut glib::String) {
    //    unsafe { TODO: call ibus_sys:ibus_xml_output() }
    //}

    pub fn parse_buffer(buffer: &str) -> Option<XML> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ibus_sys::ibus_xml_parse_buffer(buffer.to_glib_none().0))
        }
    }

    pub fn parse_file(name: &str) -> Option<XML> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ibus_sys::ibus_xml_parse_file(name.to_glib_none().0))
        }
    }
}
